name: Package EXE with PyInstaller - Windows

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
        with:
          path: .

      - uses: actions/upload-artifact@v4
        with:
          name: TFC_Alloy_Calculator
          path: dist/windows/TFC Alloy Calculator.exe

#      - name: Create release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref_name }}
#          release_name: Release ${{ github.ref_name }}
#          draft: false
#          prerelease: true

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/windows/TFC Alloy Calculator.exe
          asset_name: TFC Alloy Calculator.exe
          asset_content_type: application/octet-stream