name: Package EXE with PyInstaller - Windows

on:
  push:
    branches: [ dev-workflow ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: dist/ # or path/to/artifact